### ISSUE TITLE
Get error when downloading vep data

### ISSUE THREAD

**Issue by liuyq123** [songlab-cal/gpn#1]
Hi, thank you for such great work !

I got an error when I ran the `snakefile` in `vep`. Here's the message:
<img width="710" alt="Screen Shot 2022-10-07 at 11 36 20 PM" src="https://user-images.githubusercontent.com/47292066/194686286-5c0c527b-aaff-49a8-b59e-a603fd81b118.png">
Can you take a look at it? Thank you

**Comment by gonzalobenegas** [comment]
Thank you for your interest in our work!
Sorry about that, I'm planning to polish the code in the next 1-2 weeks.

Meanwhile, you could manually download the file from here: http://ftp.ensemblgenomes.org/pub/plants/release-53/variation/vcf/arabidopsis_thaliana/arabidopsis_thaliana_incl_consequences.vcf.gz

**Comment by liuyq123** [comment]
Thank you!

**Comment by liuyq123** [comment]
Hi, Gonzalo 

I got another error when downloading vep data.
<img width="947" alt="Screen Shot 2023-01-12 at 2 39 07 PM" src="https://user-images.githubusercontent.com/47292066/212164666-19d19276-953c-469a-a817-18271dde5fa9.png">


If I change the "Chr" to "ChrChr" in line 102, then this error would disappear. But I don't know if this change would affect other analyses. Do you have any suggestions on how to deal with this error?

Thank you!

**Comment by gonzalobenegas** [comment]
Hi, sorry about this, we changed the reference a couple of times and I didn't update this... You would just need to make sure  "variants/filt.bed.gz" and "tair10.fa" have the same format, "1" instead of "Chr1" or "chr1".

It's possible that you would need to do this kind of renaming in some of the jupyter notebooks downstream. We are currently polishing the code a lot, and planning on releasing all the datasets in HuggingFace as well so they can be downloaded with one line of code. It might take a month though, I'm sorry this is not as fast as I thought!

**Comment by liuyq123** [comment]
Thanks a lot!
